### ISSUE TITLE
[Bug] 插件开发文档多处文字描述错误

### ISSUE THREAD

**Issue by 100tk** [eagle-app/eagle-desktop-closed-beta#4]
### 🎑 截圖或測試檔案
![20230110112451](https://user-images.githubusercontent.com/55040658/211455492-b387e08c-b006-42fe-8506-3d0f6a73f686.png)
![20230110112721](https://user-images.githubusercontent.com/55040658/211455497-ef72f3e8-f40e-47ac-b313-394a27f9e6ff.png)
@Augus

**Comment by Augus** [comment]
@t100tk 感谢校正，已经修改完成啦！
